Repository raghusaripalli/GatorGiveaway, pull requests merged in 2022-02, with the labels that each got.

#8 updated code for backend
  backend/webapp/main.go
Labels: done

#14 Added logout and Read posts APIS Closes #9
  backend/webapp/go.mod
  backend/webapp/go.sum
  backend/webapp/main.db
  backend/webapp/main.go
  backend/webapp/model/product.go
  backend/webapp/views/auth.go
  backend/webapp/views/seller.go
Labels: done

#15 CRUD APIs for seller
  backend/webapp/main.db
  backend/webapp/main.go
  backend/webapp/model/product.go
  backend/webapp/views/seller.go
Labels: done

#18 Merged login and resgister UI pages.
  frontend/package-lock.json
  frontend/package.json
  frontend/public/2gators.jfif
  frontend/public/index.html
  frontend/src/App.js
  frontend/src/components/Home/Home.js
  frontend/src/index.js
Labels: done

#23 Added Read and Edit UI
  backend/webapp/main.db
  backend/webapp/main.go
  frontend/src/App.js
  frontend/src/components/Home/Home.js
Labels: done

#25 Added User operaions
  backend/webapp/main.db
  backend/webapp/main.go
  backend/webapp/views/auth.go
Labels: done, User Stories

#27 Add CSS to UI
  backend/webapp/main.db
  frontend/public/index.html
  frontend/src/components/Home/Home.js
Labels: done

#47 Adde Username and Server validations
  backend/.gitignore
  backend/webapp/views/auth.go
  frontend/src/App.js
Labels: enhancement

#48 Added validations for login and added email field in front end
  backend/webapp/views/auth.go
  frontend/src/App.js
Labels: User Stories

#49 Read from S3
  frontend/src/components/Home/Home.js
Labels: enhancement, User Stories

#62 Buyer read api
  backend/webapp/main.go
  backend/webapp/views/buyer.go
Labels: User Stories
