Repository raghusaripalli/GatorGiveaway, pull requests merged in 2022-03, with the labels that each got.

#64 Allowed user to login email, duplicate email check
  backend/webapp/views/auth.go
Labels: User Stories

#68 Added Contact Us page with email feature
  frontend/package-lock.json
  frontend/package.json
  frontend/public/index.html
  frontend/src/components/AboutUs/AboutUs.css
  frontend/src/components/AboutUs/AboutUs.js
  frontend/src/components/ContactUs/ContactUs.css
  frontend/src/components/ContactUs/ContactUs.js
Labels: User Stories

#74 Setup test strucutre
  backend/webapp/go.mod
  backend/webapp/main.go
  backend/webapp/user_test.go
Labels: User Stories

#76 Added Jest Unit test cases for UI
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.js
  frontend/src/App.test.js
  frontend/src/components/AboutUs/AboutUs.css
  frontend/src/components/AboutUs/AboutUs.js
  frontend/src/components/AboutUs/__test__/AboutUs.test.js
  frontend/src/components/ContactUs/ContactUs.css
  frontend/src/components/ContactUs/ContactUs.js
  frontend/src/components/ContactUs/__test__/ContactUs.test.js
  frontend/src/components/Footer/Footer.css
  frontend/src/components/Footer/__test__/Footer.test.js
  frontend/src/components/Header/Header.js
  frontend/src/components/Header/__test__/Header.test.js
  frontend/src/components/Login/Login.js
Labels: unit-testing

#79 Tested user APIS - GetUseryId GetUserByUsername
  backend/webapp/user_test.go
  backend/webapp/views/auth.go
Labels: unit-testing

#82 Mock API test for Seller Read Pass case, Seller Create Post pass and …
  backend/webapp/post_test.go
  frontend/package-lock.json
Labels: testing

#83 Added testcases for login, register and deletion of user
  backend/webapp/main.go
  backend/webapp/user_test.go
  backend/webapp/view_auth_test.go
  backend/webapp/views/auth.go
Labels: done

#101 Created a Sprint 3.md file
  Sprint3.md
Labels: documentation

#102 Added Order Model, Migrated it using GORM
  backend/webapp/main.go
  backend/webapp/model/order.go
Labels: User Stories, backend, API

#103 Added API for placing an order
  backend/webapp/main.go
  backend/webapp/model/order.go
  backend/webapp/views/orders.go
Labels: User Stories, backend, API

#108 API for cancelling the user order
  backend/webapp/main.go
  backend/webapp/model/order.go
  backend/webapp/views/orders.go
Labels: done
