Repository raghusaripalli/GatorGiveaway, pull requests merged in 2022-04, with the labels that each got.

#115 Favorites seperate tab created and working completely
  frontend/src/App.js
  frontend/src/components/Favorites/Favorites.js
Labels: User Stories

#118 Cart added to post and top nav bar
  frontend/src/App.js
  frontend/src/components/Cart/Cart.js
  frontend/src/components/Header/Header.js
  frontend/src/components/Home/Home.js
Labels: ui-react

#122 Added API to get a particular order details
  backend/webapp/main.go
  backend/webapp/views/orders.go
Labels: done

#123 Cancel order api tests
  backend/webapp/view_order_test.go
Labels: User Stories, testing, unit-testing, backend, API

#124 Added test cases(pass &fail) for fetching orders
  backend/webapp/user_test.go
  backend/webapp/view_order_test.go
  backend/webapp/view_post_test.go
  backend/webapp/views/orders.go
Labels: done, User Stories, unit-testing, backend, API

#125 Fixed bugs related to order APIs
  backend/webapp/views/orders.go
Labels: done

#126 Display added cart items in a model
  frontend/src/components/Home/Home.js
Labels: ui-react

#127 To display ordered items in a page after response on cart
  frontend/src/App.js
  frontend/src/components/Cart/Cart.js
  frontend/src/components/Header/Header.js
  frontend/src/components/Orders/Orders.js
Labels: ui-react

#128 Display changes to Cart page
  frontend/src/components/Home/Home.js
Labels: enhancement, ui-react

#136 API to retreive tags of all posts
  backend/webapp/main.go
  backend/webapp/model/product.go
  backend/webapp/views/seller.go
  backend/webapp/views/tags.go
Labels: done, backend, API

#138 Added API to retreive tags of a particular post.
  backend/webapp/main.go
  backend/webapp/views/tags.go
Labels: done, backend, API

#146 Feature/tags
  backend/webapp/main.go
  backend/webapp/user_test.go
  backend/webapp/view_comment_tags_test.go
  backend/webapp/views/seller.go
  backend/webapp/views/tags.go
Labels: enhancement, done, backend, API

#148 Invalid login message display changes.
  frontend/src/components/Login/Login.js
Labels: in progress, ui-react

#150 JTest added for Footer and Header components along with home button at Top bar.
  frontend/src/components/Footer/_test_/Footer.test.js
  frontend/src/components/Header/Header.js
  frontend/src/components/Header/__test__/Header.test.js
Labels: in progress, ui-react, testing, unit-testing

#152 Replace localhost link from frontend to Azure link for API calls as part of deployment.
  frontend/src/components/Favorites/Favorites.js
  frontend/src/components/Header/Header.js
  frontend/src/components/Home/Home.js
  frontend/src/components/Login/Login.js
  frontend/src/components/Orders/Orders.js
  frontend/src/components/Register/Register.js
Labels: ui-react, deployment

#154 Cypress test to delete post
  frontend/cypress/integration/deletepost.js
  frontend/src/components/Login/Login.js
Labels: ui-react, testing, cypress
